//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tourisme
{
    using System;
    using System.Collections.Generic;
    
    public partial class site
    {
        public string NumSite { get; set; }
        public string NomSite { get; set; }
        public string Lieu { get; set; }
        public Nullable<int> TarifJournaliere { get; set; }
    }
}
