//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tourisme
{
    using System;
    using System.Collections.Generic;
    
    public partial class visite
    {
        public string NumSite { get; set; }
        public string NumVisiteur { get; set; }
        public Nullable<int> NbJours { get; set; }
        public System.DateTime DateVisite { get; set; }
        public int id { get; set; }
    }
}
